name: On push to production

on:
  pull_request:
    branches:
      - release

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build docker image
        run: |
          docker build -t my-package --platform linux/x86_64 --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} .

      - name: Run docker image
        run: npm start
